name: WildPets
version: 1.3-alpha-1
main: dansplugins.wildpets.WildPets
api-version: 1.13
author: DanTheTechMan

commands:
  wildpets:
  wp:

permissions:
  wp.help:
    default: true
  wp.tame:
    default: true
  wp.select:
    default: true
  wp.rename:
    default: true
  wp.info:
    default: true
  wp.stay:
    default: true
  wp.wander:
    default: true
  wp.list:
    default: true
  wp.list.others:
    default: true
  wp.call:
    default: true
  wp.setfree:
    default: true
  wp.locate:
    default: true
  wp.follow:
    default: true
  wp.stats:
    default: true
  wp.lock:
    default: true
  wp.unlock:
    default: true
  wp.checkaccess:
    default: true
  wp.grantaccess:
    default: true
  wp.revokeaccess:
    default: true
  wp.config:
    default: op