name: WildPets
version: '${project.version}'
main: dansplugins.wildpets.WildPets
api-version: 1.13
author: DanTheTechMan
description: Wild Pets is an open source minecraft plugin that allows players to tame any entity in the game so long as their configuration is enabled.

commands:
  wildpets:
  wp:

permissions:
  wp:
    default: true
  wp.help:
    default: true
  wp.tame:
    default: true
  wp.select:
    default: true
  wp.rename:
    default: true
  wp.info:
    default: true
  wp.wander:
    default: true
  wp.list:
    default: true
  wp.list.others:
    default: true
  wp.call:
    default: true
  wp.setfree:
    default: true
  wp.locate:
    default: true
  wp.follow:
    default: true
  wp.stats:
    default: true
  wp.lock:
    default: true
  wp.unlock:
    default: true
  wp.gather:
    default: true
  wp.config:
    default: op