name: WildPets
version: 1.0-beta-1
main: dansplugins.wildpets.WildPets
api-version: 1.13

commands:
  wildpets:
  wp:

permissions:
  wp.help:
    default: true
  wp.tame:
    default: true
  wp.select:
    default: true
  wp.rename:
    default: true
  wp.info:
    default: true
  wp.stay:
    default: true
  wp.wander:
    default: true
  wp.list:
    default: true
  wp.call:
    default: true
  wp.setfree:
    default: true
  wp.locate:
    default: true
  wp.config:
    default: op